# Generated by Django 2.0.4 on 2018-05-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180501_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='createor',
            new_name='creator',
        ),
    ]
